<?php
define('APP_ROOT',dirname(__DIR__));
require APP_ROOT.'/config/config.php';
require APP_ROOT.'/core/Database.php';
require APP_ROOT.'/core/Controller.php';
require APP_ROOT.'/core/Auth.php';
require APP_ROOT.'/core/Router.php';
$router=new Router();
$router->get('/','AuthController@login');
$router->get('/login','AuthController@login');
$router->post('/login','AuthController@authenticate');
$router->get('/logout','AuthController@logout');
$router->get('/dashboard','DashboardController@index');

$router->get('/clients','ClientController@index');
$router->get('/clients/create','ClientController@create');
$router->post('/clients/store','ClientController@store');
$router->get('/suppliers','SupplierController@index');
$router->get('/suppliers/create','SupplierController@create');
$router->post('/suppliers/store','SupplierController@store');
$router->get('/requirements','RequirementController@index');
$router->get('/requirements/create','RequirementController@create');
$router->post('/requirements/store','RequirementController@store');
$router->get('/requirements/edit','RequirementController@edit');
$router->post('/requirements/update','RequirementController@update');
$router->get('/requirements/delete','RequirementController@delete');
$router->get('/candidate/apply','CandidateController@apply');
$router->post('/candidate/apply','CandidateController@store');
$router->get('/candidates','CandidateController@index');
$router->get('/candidates/view','CandidateController@details');
$router->post('/candidates/status','CandidateController@updateStatus');
$router->get('/matching','MatchingController@index');
$router->post('/matching/shortlist','MatchingController@shortlist');
$router->get('/matching/status','MatchingController@status');
$router->get('/deployments','DeploymentController@index');
$router->get('/deployments/create','DeploymentController@create');
$router->post('/deployments/store','DeploymentController@store');
$router->get('/deployments/edit','DeploymentController@edit');
$router->post('/deployments/update','DeploymentController@update');
$router->get('/deployments/delete','DeploymentController@delete');
$router->run();
